### ISSUE TITLE
Game crashes when firing Wave beam up in some underwater rooms

### ISSUE THREAD

**Issue by Nimta** [AbyssalCreature/AM2R-Re-Splashed#8]
When beams create a water splash out of map boundaries, the game cannot locate them(?) and simply crashes. Without Wave beam, this isn't a problem, but with it, rooms that are fully submerged will crash your game if/when you fire upwards. Mainly a problem in Distrobution Station, tested to crash in Seris' boss room, and a couple rooms below and nearby.
```
ERROR in 
action number 1
of  Step Event0
for object oSmallSplash:
Unable to find any instance for object index '366' name 'oWater'
at gml_Object_oSmallSplash_Step_0
```

**Comment by AbyssalCreature** [comment]
I'm assuming this is on the testing version that I posted and forgot about. This issue has been solved on devbuild, closing issue.

**Comment by Nimta** [comment]
It's on the Sep 29th devbuild, marked as prerelease
